package grafana

func Search() []string {
	return []string{
		"daus",
		"daily_transaction_volume",
		"new_user_profitable_rate",
		"user_repurchase_rate",

		"user_actual_active_dates_distribution",
		"user_total_active_dates_distribution",

		"new_user_spending_usd_distribution",
		"new_rentee_spending_usd_distribution",
		"new_purchaser_spending_usd_distribution",
		"new_hybrider_spending_usd_distribution",
		"new_rentee_spending_token_distribution",
		"new_purchaser_spending_token_distribution",
		"new_hybrider_spending_token_distribution",

		"new_user_profit_usd_distribution",
		"new_rentee_profit_usd_distribution",
		"new_purchaser_profit_usd_distribution",
		"new_hybrider_profit_usd_distribution",
		"new_rentee_profit_token_distribution",
		"new_purchaser_profit_token_distribution",
		"new_hybrider_profit_token_distribution",

		"new_user_type",

		"new_user_profitable_days",
		"new_rentee_profitable_days",
		"new_purchaser_profitable_days",
		"new_hybrider_profitable_days",
		"whale_sort_by_gain",
		"whale_sort_by_profit",
		"whale_sort_by_spending",

		"daus2",
		"daily_transaction_volume2",
		"new_user_profitable_rate2",
		"user_repurchase_rate2",
		"user_actual_active_dates_distribution2",
		"user_total_active_dates_distribution2",
		"new_user_type2",
		"new_user_spending_usd_distribution2",
		"new_rentee_spending_usd_distribution2",
		"new_rentee_spending_token_distribution2",
		"new_purchaser_spending_usd_distribution2",
		"new_purchaser_spending_token_distribution2",
		"new_hybrider_spending_usd_distribution2",
		"new_hybrider_spending_token_distribution2",
		"new_user_profit_usd_distribution2",
		"new_rentee_profit_usd_distribution2",
		"new_rentee_profit_token_distribution2",
		"new_purchaser_profit_usd_distribution2",
		"new_purchaser_profit_token_distribution2",
		"new_hybrider_profit_usd_distribution2",
		"new_hybrider_profit_token_distribution2",
		"new_user_profitable_days2",
		"new_rentee_profitable_days2",
		"new_purchaser_profitable_days2",
		"new_hybrider_profitable_days2",
		"whale_sort_by_gain2",
		"whale_sort_by_profit2",
		"whale_sort_by_spending2",
	}
}
